import path from "node:path";
import { defineVideo } from "termcut";

// The frames the landing-page walkthrough shows: one SVG snapshot after each step of the script the page
// explains. Regenerated by `bun run media`; the outputs are committed so the site builds without a WebView.
const out = path.resolve(import.meta.dir, "..", "src", "assets", "walkthrough");
const frame = (n: number) => path.join(out, `step-${n}.svg`);

export default defineVideo(
  {
    output: [path.join(out, "walkthrough.svg")],
    cast: path.join(out, "walkthrough.cast"),
    cols: 66,
    rows: 15,
    theme: "catppuccin-mocha",
    windowBar: "none",
    margin: 0,
    padding: 14,
    borderRadius: 0,
    marginFill: "transparent",
    cursor: { blink: false },
    typingSpeed: "35ms",
    endPause: "600ms",
  },
  async (t) => {
    await t.hide(async () => {
      await t.run("cd $(mktemp -d) && bun init -y >/dev/null 2>&1 && rm -f *.md");
      await t.clear();
    });
    // Each step gets its own frame: a beat before and after every mark, so marks land on distinct ticks and the
    // next keystroke is not batched into the same frame.
    await t.sleep("400ms");
    await t.snapshot(frame(1));
    await t.sleep("120ms");
    await t.run("bun --version");
    await t.sleep("400ms");
    await t.snapshot(frame(2));
    await t.sleep("120ms");
    await t.run("ls -la");
    await t.expect(/package\.json/);
    await t.sleep("400ms");
    await t.snapshot(frame(3));
    await t.sleep("120ms");
    await t.snapshot(frame(4));
    await t.sleep("120ms");
    await t.chapter("Install");
    await t.timelapse(() => t.run("bun add zod"), { speed: 8 });
    await t.sleep("400ms");
    await t.snapshot(frame(5));
    await t.sleep("120ms");
    await t.print("## Done\n\nRender it: `tcut demo.video.ts`");
    await t.sleep("400ms");
    await t.snapshot(frame(6));
  },
);
